### ISSUE TITLE
Sunpath node not creating anything

### ISSUE THREAD

**Issue by tothom** [ladybug-analysis-tools/ladybug-dynamo#17]
Hi

There seems to be a bug with the Sunpath node. There nothing coming out of its outputs even though I seems to have set it up properly.

When I copy the python script out of the custom node and I see that it is producing an error message: 

`Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 51, in <module>
  File "C:\Users\ew345\AppData\Roaming\Dynamo\Dynamo Revit\1.0\packages\Ladybug\extra\ladybugdynamo\sunpath.py", line 77, in fromLocation
SystemError: Object reference not set to an instance of an object.`

![160613-145649](https://cloud.githubusercontent.com/assets/9868784/16008211/147e74a4-3177-11e6-8d6d-10eb407aa816.png)

Regards,
Thomas

**Comment by mostaphaRoudsari** [comment]
Hi @tothom, Thank you for reporting. Two questions:
1. Are you using the latest release of ladybug for Dynamo? 0.1.2?
2. What is timestep input in analysis period?

**Comment by tothom** [comment]
Hi
1. The version of Ladybug is 0.1.2
2. Timestep is set to 1

**Comment by mostaphaRoudsari** [comment]
@tothom you found a specific case where ladybug datetime fails. I will get this fixed soon. For now if you set the timezone to 1.1 sunpath it will work. This should effect sun positions by less than a degree.

![image](https://cloud.githubusercontent.com/assets/2915573/16013148/569b21ce-315a-11e6-9034-9d072706d99e.png)

Also since you're trying to create +4800 sun positions make sure to set the preview **off** for the sunpath otherwise it can take a very long time in Dynamo. I'm not sure how dynamo preview exacyly works. We may need not to create the spheres for cases with so many sun positions.

**Comment by tothom** [comment]
Hi @mostaphaRoudsari 

Thanks! It works now with timezone set to 1.1.

By the way, I only create 17 sun vectors. The _startDay_ and _endDay_ are the same, and so are _startMonth_ and _endMonth_.

**Comment by mostaphaRoudsari** [comment]
This is fixed in the source code. Will close it after updating Ladybug-Dynamo node.
